ALTER TABLE `Team`
  ADD COLUMN `ownerId` INT NOT NULL,
  ADD COLUMN `deletedAt` DATETIME(3) NULL,
  ADD CONSTRAINT `Team_ownerId_fkey` FOREIGN KEY (`ownerId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
